import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#e6beaa",
        "primary": "#261206",
        "primary-container": "#3e2618",
        "tertiary-container": "#2d2c29",
        "inverse-surface": "#31302d",
        "secondary-fixed-dim": "#ffb875",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e6e2dd",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#50443f",
        "inverse-primary": "#e6beaa",
        "on-surface": "#1c1c19",
        "surface-container-high": "#ebe8e3",
        "error": "#ba1a1a",
        "outline": "#82746e",
        "on-primary-container": "#af8b79",
        "surface": "#fdf9f4",
        "error-container": "#ffdad6",
        "surface-tint": "#765847",
        "surface-dim": "#ddd9d5",
        "on-secondary-fixed": "#2d1600",
        "secondary-container": "#fda957",
        "secondary": "#8d4f00",
        "primary-fixed": "#ffdbc9",
        "surface-container-low": "#f7f3ee",
        "on-background": "#1c1c19",
        "surface-container-highest": "#e6e2dd",
        "on-primary-fixed-variant": "#5c4131",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1c1c19",
        "on-secondary-container": "#713e00",
        "on-primary-fixed": "#2b1609",
        "on-tertiary-fixed-variant": "#484743",
        "tertiary-fixed-dim": "#c9c6c1",
        "on-error-container": "#93000a",
        "outline-variant": "#d4c3bc",
        "secondary-fixed": "#ffdcc0",
        "surface-variant": "#e6e2dd",
        "tertiary": "#181715",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f4f0eb",
        "on-secondary": "#ffffff",
        "background": "#fdf9f4",
        "surface-container": "#f1ede8",
        "surface-bright": "#fdf9f4",
        "on-tertiary-container": "#95938f",
        "on-secondary-fixed-variant": "#6b3b00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "grid-margin": "64px",
        "grid-gutter": "32px",
        "content-gap": "40px",
        "section-gap": "160px",
        unit: "8px",
      },
      fontFamily: {
        serif: ["Noto Serif", "Georgia", "serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "0.04em", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.8", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.15em", fontWeight: "600" }],
      },
      animation: {
        "fade-up": "fadeUp 0.8s ease-out forwards",
        "fade-in": "fadeIn 0.6s ease-out forwards",
        "slow-zoom": "slowZoom 20s ease-in-out infinite alternate",
      },
      keyframes: {
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slowZoom: {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(1.08)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
